//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class twittercloneEntities1 : DbContext
    {
        public twittercloneEntities1()
            : base("name=twittercloneEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Following> Followings { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Tweet> Tweets { get; set; }
        public virtual DbSet<vw_TweetFollower> vw_TweetFollower { get; set; }
        public virtual DbSet<vw_Followers> vw_Followers { get; set; }
        public virtual DbSet<vw_Tweets> vw_Tweets { get; set; }
    }
}
