//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TweetFollower
    {
        public string TweetUser { get; set; }
        public long TweetId { get; set; }
        public string TweetMessage { get; set; }
        public string Follower { get; set; }
        public long TweetUserId { get; set; }
        public long FollowerId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long Id { get; set; }
    }
}
